### ISSUE TITLE
Change `volume.config` to `volume.yaml`

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#10766]
How about making it yaml like other configs? 

##  Current
```
volume=1 scheme=http size=10%
volume=2 scheme=http size=1024
```

## Proposal

- Add `volumes` as root key. 
- Convert current tag to key of each entry.

```
volumes:
  - volume: 1
    scheme: http
    size: 10%
  - volume: 2
    scheme: http
    size: 1024
````
