### ISSUE TITLE
Negative Response Caching with Proxy.config.http.negative_caching_lifetime vs TTL-in-Cache

### ISSUE THREAD

**Issue by incheoloh** [apache/trafficserver#11854]
cache.config
```
url_regex=.*    ttl-in-cache=20s
```

records.yaml
```
records:
  http:
    negative_caching_enabled: 1
    negative_caching_lifetime: 5
```

ttl-in-cache in cache.config sets a default TTL, applying this duration to cached responses regardless of the response code.
proxy.config.http.negative_caching_lifetime in records.yaml is intended to set the TTL for negative responses (e.g., 403, 404). However, if ttl-in-cache is defined in cache.config, it takes precedence and applies a TTL of 20 seconds to all responses, including 403.

Is there any way to use the value set by proxy.config.http.negative_caching_lifetime instead of the ttl set by ttl-in-cache for negative responses?
